export const POST_ARTICOLO_START= 'POST_ARTICOLO_START';
export const POST_ARTICOLO_SUCCESS= 'POST_ARTICOLO_SUCCESS';
export const POST_ARTICOLO_FAIL = 'POST_ARTICOLO_FAIL';

export const CREATE_ARTICOLO = 'CREATE_ARTICOLO';
export const SET_ARTICOLI_SUCCESS = 'SET_ARTICOLI_SUCCESS';
export const SET_ARTICOLI_START = 'SET_ARTICOLI_START';
export const SET_ARTICOLI_FAIL = 'SET_ARTICOLI_FAIL';
export const INIT_ARTICOLI = 'INIT_ARTICOLI';
export const RICERCA_ARTICOLI = 'RICERCA_ARTICOLI';

export const START_RICERCA = 'START_RICERCA';
export const UPDATE_ARTICOLO_SUCCESS = 'UPDATE_ARTICOLO_SUCCESS';
export const DELETE_ARTICOLO_SUCCESS = 'DELETE_ARTICOLO_SUCCESS';

export const LOGIN_START= 'LOGIN_START';
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT= 'LOGOUT';
export const SET_LOGIN_REDIRECT_PATH = 'SET_LOGIN_REDIRECT_PATH';
export const GOOGLE_AUTH_START = 'GOOGLE_AUTH_START';
export const GOOGLE_AUTH_SUCCESS= 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';

export const SEND_DATA_START= 'SEND_DATA_START';
export const SEND_DATA_SUCCESS = 'SEND_DATA_SUCCESS';
export const SEND_DATA_FAIL = 'SEND_DATA_FAIL';