export const POST_ARTICOLO_START= 'POST_ARTICOLO_START';
export const POST_ARTICOLO_SUCCESS= 'POST_ARTICOLO_SUCCESS';
export const POST_ARTICOLO_FAIL = 'POST_ARTICOLO_FAIL';
export const CREATE_ARTICOLO = 'CREATE_ARTICOLO';
export const SET_ARTICOLI = 'SET_ARTICOLI';
export const INIT_ARTICOLI = 'INIT_ARTICOLI';
export const RICERCA_ARTICOLI = 'RICERCA_ARTICOLI'
